version: '3.8'

services:
  hydra:
    build:
      context: ./hydra
      dockerfile: Dockerfile
    image: custom-hydra:latest
    ports:
      - "4444:4444" # Public
      - "4445:4445" # Admin
    restart: unless-stopped

  keto:
    build:
      context: ./keto
      dockerfile: Dockerfile
    image: custom-keto:latest
    ports:
      - "4466:4466" # Read API
      - "4467:4467" # Write API
    restart: unless-stopped
